modLoader="javafml"
loaderVersion="[32,)"
license="ARR"

[[mods]]
	modId="allthewoods"
	version="${version}"
	displayName="All the Woods"
	authors="JTK222"
	description='''A collection of wood types from various mods'''

[[dependencies]]
	modId="forge"
	mandatory=true
	versionRange="[32,)"
	ordering="NONE"
	side="BOTH"

[[dependencies]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16,)"
	ordering="NONE"
	side="BOTH"

[modproperties.allthewoods]
    margMaterialFiles=[
        #"data/allthewoods/material/oak.json"
    ]
